---
- name: metricbeat
  hosts: all
  vars:
    metricbeat_conf_docker_hosts:
      - unix:///var/run/docker.sock
    metricbeat_conf_postgresql_hosts:
      - postgres://localhost:5432
    metricbeat_conf_postgresql_user: root
    metricbeat_conf_postgresql_pass: pass
    metricbeat_conf_nginx_hosts:
      - http://127.0.0.1
    metricbeat_conf_nginx_status_path: nginx_status
  roles:
     - role: nephelaiio.metricbeat